@php($part = $part ?? null)
@if($errors->any())
<div role="alert" class="rounded-xl bg-red-50 p-4 text-red-800"><p class="font-semibold">Revise los datos del formulario.</p><ul class="mt-2 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<p class="text-sm text-slate-600">Campos con * obligatorios. Los precios se registran en colones.</p>
<div class="grid gap-5 sm:grid-cols-2">
@foreach(['code'=>['Código *',40], 'name'=>['Nombre *',150]] as $field=>$settings)
<div><label for="{{ $field }}" class="block text-sm font-semibold text-slate-700">{{ $settings[0] }}</label><input type="text" name="{{ $field }}" id="{{ $field }}" required maxlength="{{ $settings[1] }}" value="{{ old($field,$part?->{$field} ?? '') }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 py-3" @error($field) aria-invalid="true" @enderror>@error($field)<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
@endforeach
<div><label for="price" class="block text-sm font-semibold text-slate-700">Precio de venta (₡) *</label><input type="number" name="price" id="price" min="0" max="9999999999.99" step="0.01" inputmode="decimal" required value="{{ old('price',$part?->price ?? '') }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 py-3">@error('price')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div><label for="minimum_quantity" class="block text-sm font-semibold text-slate-700">Existencia mínima *</label><input type="number" id="minimum_quantity" name="minimum_quantity" min="0" max="1000000" step="1" inputmode="numeric" required value="{{ old('minimum_quantity',$part?->minimum_quantity ?? 0) }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 py-3">@error('minimum_quantity')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div><label for="spare_part_brand_id" class="block text-sm font-semibold text-slate-700">Marca</label><select id="spare_part_brand_id" name="spare_part_brand_id" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">Sin marca especificada</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('spare_part_brand_id',$part?->spare_part_brand_id ?? '') == $brand->id)>{{ $brand->name }}{{ $brand->active ? '' : ' (inactiva)' }}</option>@endforeach</select>@error('spare_part_brand_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div><label for="active" class="block text-sm font-semibold text-slate-700">Estado *</label><select name="active" id="active" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="1" @selected((string)old('active',$part?->active ?? 1) === '1')>Activo</option><option value="0" @selected((string)old('active',$part?->active ?? 1) === '0')>Inactivo</option></select></div>
<div class="sm:col-span-2"><label for="description" class="block text-sm font-semibold text-slate-700">Descripción / compatibilidad</label><textarea name="description" id="description" maxlength="250" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Ej.: compatible con Honda CB190">{{ old('description',$part?->description ?? '') }}</textarea></div>
</div>
<div class="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{{ $part ? 'Existencias actuales: '.$part->stock_quantity.' unidades.' : 'El repuesto inicia con cero existencias.' }} Para modificar el stock, registre una entrada, salida o ajuste desde su detalle.</div>
@can('manage-security')<a href="{{ route('spare-part-brands.index') }}" class="inline-flex min-h-12 items-center font-semibold text-amber-700">¿Falta una marca? Administrar marcas de repuestos →</a>@endcan