@extends('layouts.app')
@section('title','Detalle del repuesto')
@section('app-contents')
@if(session('success'))<x-alert :message="session('success')" />@endif
<div class="mt-6"><div class="mb-5 flex flex-wrap gap-3"><a href="{{ route('spareparts.index') }}" class="inline-flex min-h-12 items-center text-slate-700">← Volver a repuestos</a>@can('module-access',['inventory','edit'])<a href="{{ route('spareparts.edit',$part) }}" class="inline-flex min-h-12 items-center rounded-xl bg-amber-50 px-4 py-3 font-semibold text-amber-800">{{ $part->active ? 'Editar' : 'Editar / Reactivar' }}</a>@endcan @can('module-access',['inventory','delete'])
@if($part->active)
<form action="{{ route('spareparts.destroy',$part) }}" method="POST" onsubmit="return confirm('¿Desea desactivar el repuesto? Se conservarán sus existencias e historial.')">@csrf @method('DELETE')<button type="submit" class="min-h-12 rounded-xl px-4 py-3 text-red-700">Desactivar</button></form>
@endif
@endcan</div>
<div class="grid gap-5 lg:grid-cols-2"><section class="min-w-0 rounded-2xl bg-slate-900 p-5 text-white sm:p-6"><p class="break-all font-mono text-sm text-amber-300">{{ $part->code }} · {{ $part->active ? 'Activo' : 'Inactivo' }}</p><h2 class="mt-3 break-words text-2xl font-bold">{{ $part->name }}</h2><p class="mt-2 text-slate-300">{{ $part->brand?->name ?? 'Sin marca especificada' }}</p><p class="mt-4 break-words text-sm text-slate-300">{{ $part->description ?: 'Sin descripción.' }}</p><div class="mt-6 grid grid-cols-2 gap-4"><div><p class="text-sm text-slate-300">Precio de venta</p><p class="mt-1 break-all text-xl font-bold">₡{{ number_format((float)$part->price,2,',','.') }}</p></div><div><p class="text-sm text-slate-300">Existencias</p><p class="mt-1 text-2xl font-bold text-amber-300">{{ $part->stock_quantity }}</p><p class="text-xs text-slate-300">Mínimo: {{ $part->minimum_quantity }}</p></div></div></section>
@can('module-access',['inventory','edit'])
<section class="rounded-2xl border border-slate-200 p-5"><h2 class="text-lg font-bold text-slate-900">Registrar movimiento</h2>
@if($errors->any())<div role="alert" class="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
@if($part->active)
<form action="{{ route('spareparts.movements.store',$part) }}" method="POST" class="mt-4 space-y-4">@csrf <input type="hidden" name="request_token" value="{{ old('request_token', (string)Illuminate\Support\Str::uuid()) }}"><div class="grid gap-3 sm:grid-cols-2"><div><label for="type" class="block text-sm font-semibold">Tipo *</label><select id="type" name="type" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 py-3"><option value="IN" @selected(old('type') === 'IN')>Entrada (+)</option><option value="OUT" @selected(old('type') === 'OUT')>Salida (−)</option>@can('manage-security')<option value="ADJUST" @selected(old('type') === 'ADJUST')>Ajuste por conteo</option>@endcan</select></div><div><label for="quantity" class="block text-sm font-semibold">Cantidad / conteo *</label><input type="number" name="quantity" id="quantity" min="0" max="1000000" step="1" inputmode="numeric" required value="{{ old('quantity') }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 py-3"></div></div><p class="text-xs leading-relaxed text-slate-500">Entrada y salida: unidades que se agregan o retiran. Ajuste: total de unidades contadas; puede ser cero. Las entradas y salidas deben ser mayores que cero.</p><div><label for="notes" class="block text-sm font-semibold">Motivo / referencia *</label><textarea id="notes" name="notes" maxlength="250" rows="2" required class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Ej.: compra al proveedor, devolución o pieza dañada">{{ old('notes') }}</textarea></div><button type="submit" class="min-h-12 w-full rounded-xl bg-amber-400 px-5 py-3 font-semibold">Registrar movimiento</button></form>
@else
<p class="mt-4 text-sm text-slate-600">El repuesto está inactivo. Reactívelo desde Editar antes de registrar movimientos.</p>
@endif
</section>
@endcan
</div>
<section class="mt-8"><h2 class="text-xl font-bold text-slate-900">Historial de movimientos</h2><p class="mt-2 text-sm text-slate-500">Se conserva el responsable, motivo y saldos de cada movimiento.</p>
<form method="GET" action="{{ route('spareparts.show',$part) }}" class="my-5 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-5"><div><label for="history-type" class="block text-sm font-semibold">Tipo</label><select name="type" id="history-type" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3 py-3"><option value="">Todos</option>@foreach(['IN'=>'Entrada','OUT'=>'Salida','ADJUST'=>'Ajuste'] as $key=>$label)<option value="{{ $key }}" @selected(request('type') === $key)>{{ $label }}</option>@endforeach</select></div>@foreach(['from'=>'Desde','to'=>'Hasta'] as $field=>$label)<div><label for="{{ $field }}" class="block text-sm font-semibold">{{ $label }}</label><input type="date" id="{{ $field }}" name="{{ $field }}" value="{{ request($field) }}" class="mt-2 min-h-12 w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-3"></div>@endforeach<button type="submit" class="min-h-12 self-end rounded-xl bg-slate-800 px-4 py-3 font-semibold text-white">Filtrar</button><a href="{{ route('spareparts.show',$part) }}" class="inline-flex min-h-12 items-center justify-center self-end rounded-xl border border-slate-300 px-4 py-3">Limpiar</a></form>
<div class="grid gap-3 md:grid-cols-2">
@forelse($movements as $movement)
<article class="min-w-0 rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap justify-between gap-2"><span class="font-bold {{ $movement->type === 'OUT' ? 'text-red-700' : 'text-emerald-800' }}">{{ ['IN'=>'Entrada','OUT'=>'Salida','ADJUST'=>'Ajuste'][$movement->type] ?? $movement->type }} · {{ $movement->quantity }} unidades</span><span class="text-xs text-slate-500">{{ $movement->date->format('d/m/Y H:i') }}</span></div><p class="mt-2 text-sm text-slate-600">Saldo: {{ $movement->previous_balance }} → <strong>{{ $movement->new_balance }}</strong></p><p class="mt-2 break-words text-sm text-slate-800">{{ $movement->notes }}</p><p class="mt-2 break-words text-xs text-slate-500">{{ $movement->user->name }} · Movimiento #{{ $movement->id }}</p></article>
@empty
<p class="rounded-xl bg-slate-50 p-6 text-slate-500 md:col-span-2">No hay movimientos con estos filtros.</p>
@endforelse
</div><div class="mt-6">{{ $movements->links() }}</div></section></div>
@endsection
