@php($order = $order ?? null)
@if($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-4 text-red-800"><p class="font-semibold">Revise los datos.</p><ul class="mt-2 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<p class="text-sm text-slate-600">Seleccione primero al cliente; la lista de motos mostrará únicamente sus vehículos.</p>
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="customer_id" class="block text-sm font-semibold">Cliente *</label><select id="customer_id" name="customer_id" required class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="">Seleccione un cliente</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$order?->customer_id) == $customer->id)>{{ $customer->name }} · {{ $customer->identification_number }}</option>@endforeach</select>@error('customer_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="vehicle_id" class="block text-sm font-semibold">Moto *</label><select id="vehicle_id" name="vehicle_id" required class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="">Seleccione una moto</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" data-customer="{{ $vehicle->customer_id }}" @selected(old('vehicle_id',$order?->vehicle_id) == $vehicle->id)>{{ $vehicle->license_plate }} · {{ $vehicle->brand->name }} {{ $vehicle->model }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Si no aparece, registre primero la moto del cliente.</p>@error('vehicle_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="mechanic_id" class="block text-sm font-semibold">Mecánico</label><select id="mechanic_id" name="mechanic_id" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="">Sin asignar</option>@foreach($mechanics as $mechanic)<option value="{{ $mechanic->id }}" @selected(old('mechanic_id',$order?->mechanic_id) == $mechanic->id)>{{ $mechanic->name }}</option>@endforeach</select>@error('mechanic_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="order_status_id" class="block text-sm font-semibold">Estado *</label><select id="order_status_id" name="order_status_id" required class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4">@foreach($statuses as $status)<option value="{{ $status->id }}" @selected(old('order_status_id',$order?->order_status_id ?? $statuses->firstWhere('name','Recibido')?->id) == $status->id)>{{ $status->name }}</option>@endforeach</select>@error('order_status_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="received_at" class="block text-sm font-semibold">Fecha y hora de recepción *</label><input type="datetime-local" id="received_at" name="received_at" required value="{{ old('received_at',$order?->received_at?->format('Y-m-d\TH:i') ?? now()->format('Y-m-d\TH:i')) }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4">@error('received_at')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="labor_cost" class="block text-sm font-semibold">Mano de obra (₡) *</label><input type="number" id="labor_cost" name="labor_cost" min="0" max="9999999999.99" step="0.01" inputmode="decimal" required value="{{ old('labor_cost',$order?->labor_cost ?? 0) }}" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4">@error('labor_cost')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="description" class="block text-sm font-semibold">Trabajo solicitado / síntomas *</label><textarea id="description" name="description" rows="3" maxlength="500" required class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">{{ old('description',$order?->description) }}</textarea>@error('description')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="diagnosis" class="block text-sm font-semibold">Diagnóstico y trabajo realizado</label><textarea id="diagnosis" name="diagnosis" rows="3" maxlength="500" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">{{ old('diagnosis',$order?->diagnosis) }}</textarea>@error('diagnosis')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    @if($order)<div class="sm:col-span-2"><label for="status_notes" class="block text-sm font-semibold">Detalle del cambio de estado</label><input type="text" id="status_notes" name="status_notes" maxlength="250" value="{{ old('status_notes') }}" placeholder="Obligatorio cuando cambia el estado" class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4">@error('status_notes')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>@endif
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const customer=document.getElementById('customer_id'),vehicle=document.getElementById('vehicle_id'),options=[...vehicle.options];const filter=()=>{const selected=customer.value;options.forEach((option,index)=>{if(index===0)return;option.hidden=!selected||option.dataset.customer!==selected;option.disabled=option.hidden});if(vehicle.selectedOptions[0]?.disabled)vehicle.value=''};customer.addEventListener('change',filter);filter()});</script>
